version: "3.7"

services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: laravel-app
        restart: unless-stopped
        working_dir: /var/www/html
        volumes:
            - .:/var/www/html
        depends_on:
            - db
        networks:
            - app-network

    db:
        image: mysql:8.0
        container_name: laravel-db
        restart: unless-stopped
        ports:
            - "3306:3306"
        environment:
            MYSQL_DATABASE: laravel_db
            MYSQL_USER: user
            MYSQL_PASSWORD: password
            MYSQL_ROOT_PASSWORD: root_password
        volumes:
            - db-data:/var/lib/mysql
        networks:
            - app-network

    nginx:
        image: nginx:stable-alpine
        container_name: laravel-nginx
        restart: unless-stopped
        ports:
            - "80:80"
        volumes:
            - .:/var/www/html
            - ./nginx.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - app
        networks:
            - app-network

    adminer:
        image: adminer
        container_name: laravel-adminer
        restart: unless-stopped
        ports:
            - "8080:8080"
        networks:
            - app-network

volumes:
    db-data:

networks:
    app-network:
        driver: bridge
